"""
Dashboard Configuration File
Author: UI/UX Designer

This module contains centralized settings for the dashboard, including the 
core color palette and standardized section titles. Using these constants 
ensures a consistent visual identity and text formatting across all components 
and Plotly charts generated by the Viz Expert.
"""

# ==========================================================================
# Core Project Color Palette
# ==========================================================================
COLORS = {
    'primary': '#3498db',    # Primary Blue: Used for main data traces, highlights, and active elements.
    'secondary': '#2ecc71',  # Secondary Green: Used for positive metrics, secondary data traces, or success states.
    'danger': '#e74c3c',     # Danger Red: Used for negative metrics, alerts, or emphasizing specific low values.
    'background': '#f4f6f9', # Main Background: A soft light gray for the overall dashboard layout.
    'text': '#2c3e50',       # Default Text Color: Dark slate gray for high readability.
    'card_bg': '#ffffff'     # Card Background: Pure white for KPI and Chart placeholder backgrounds.
}

# ==========================================================================
# Standardized Section Titles
# ==========================================================================
TITLES = {
    'main': "Ford GoBike Dashboard",
    'kpi': "Key Performance Indicators",
    'map': "Station Analysis",
    'trends': "User Behavior Trends"
}